language: bash
solution: NUtils.sln
os: windows
install:
  - choco install dotnetcore-sdk
  - dotnet.exe restore NUtils.sln
script:
  - dotnet.exe build -c Release
  - dotnet.exe test -c Release NUtils.Tests/NUtils.Tests.csproj
